ERROR_AUTHENTICATING_USER = "There was an error authenticating the user!"
USER_AUTH_TOKEN_UPDATE_SUCCESS="Access token and refresh token updated for user with ID"
USER_NOT_FOUND="User not found!"
USER_WITH_ID_NOT_FOUND="The user id with not found! Invalid user id:"
ERROR_FETCHING_ANIME="Error fetching anime!"